apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-cicd-deploy
  name: node-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-cicd-deploy
  type: NodePort
status:
  loadBalancer: {}
