pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "gautamdevgrover/node-cicd-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/gautamdevgrover/Project1.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKER_IMAGE:$IMAGE_TAG -f docker/Dockerfile .
                docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                set -e

                docker rm -f test || true

                docker run -d --name test -p 3001:3000 $DOCKER_IMAGE:$IMAGE_TAG

                success=false

                for i in {1..10}; do
                  if curl -f http://localhost:3001/health; then
                    echo "App is healthy ✅"
                    success=true
                    break
                  fi
                  echo "Waiting for app..."
                  sleep 2
                done

                docker rm -f test || true

                if [ "$success" = false ]; then
                  echo "Health check failed ❌"
                  exit 1
                fi
                '''
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS')]) {

                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin

                    docker push $DOCKER_IMAGE:$IMAGE_TAG
                    docker push $DOCKER_IMAGE:latest

                    docker logout
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    try {
                        sh '''
                        kubectl set image deployment/node-cicd-deploy \
                        node-cicd-app=$DOCKER_IMAGE:$IMAGE_TAG -n frontend

                        kubectl rollout status deployment/node-cicd-deploy -n frontend --timeout=60s
                        '''
                    } catch (Exception e) {
                        echo "Deployment failed! Rolling back..."

                        sh '''
                        kubectl rollout undo deployment/node-cicd-deploy -n frontend
                        '''

                        error("Deployment failed and rollback executed")
                    }
                }
            }
        }
    }
  post {
    success {
        emailext (
            subject: "✅ SUCCESS: Build #${BUILD_NUMBER}",
            mimeType: 'text/html',
            body: """
            <html>
            <body style="font-family: Arial;">

                <h2 style="color: green;">Build Successful 🚀</h2>

                <table border="1" cellpadding="10" cellspacing="0">
                    <tr>
                        <th>Project</th>
                        <td>${JOB_NAME}</td>
                    </tr>
                    <tr>
                        <th>Build Number</th>
                        <td>${BUILD_NUMBER}</td>
                    </tr>
                    <tr>
                        <th>Docker Image</th>
                        <td>${DOCKER_IMAGE}</td>
                    </tr>
                </table>

                <br>

                <a href="${BUILD_URL}" style="color: blue;">
                    🔗 View Build Details
                </a>

            </body>
            </html>
            """,
            to: "gautamaws777@gmail.com"
        )
    }

    failure {
        emailext (
            subject: "❌ FAILED: Build #${BUILD_NUMBER}",
            mimeType: 'text/html',
            body: """
            <html>
            <body style="font-family: Arial;">

                <h2 style="color: red;">Build Failed ❌</h2>

                <p><b>Project:</b> ${JOB_NAME}</p>
                <p><b>Build Number:</b> ${BUILD_NUMBER}</p>

                <a href="${BUILD_URL}" style="color: blue;">
                    🔗 Check Logs
                </a>

            </body>
            </html>
            """,
            to: "gautamaws777@gmail.com"
        )
    }

    always {
        sh 'docker rm -f test || true'
    }
}
}
